# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: S1 Panel add-on
version: "1.0.1"
slug: s1panel
description: S1 Panel add-on
url: "https://github.com/andrey-reshetnikov/s1panel/tree/main/s1panel"
arch:
#  - armhf
#  - armv7
#  - aarch64
  - amd64
#  - i386
init: false
map:
  - share:rw
options:
  message: "This is test..."
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  message: "str?"
image: "ghcr.io/andrey-reshetnikov/{arch}-s1panel"
webui: "http://[HOST]:[PORT:8686]"
ports:
  8686/tcp: 8686
ports_description:
  8686/tcp: Dashboard
full_access: true


