# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: S1 Panel add-on
version: "1.0.0"
slug: example
description: S1 Panel add-on
url: "https://github.com/andrey-reshetnikov/s1panel/tree/main/s1panel"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-s1panel"
